// variants/react-next/src/app/(pdp)/pdp/[slug]/page.tsx
import type { Metadata } from "next";
import { cache } from "react";
import { notFound } from "next/navigation";
import type { ReleaseDetail } from "@pm/data-contract";
import { loadDetail } from "@/lib/edge";
import { PdpArticle } from "@/lib/pdp";
import { Shell } from "@/lib/render";

// Trays are fetched through the edge Worker at REQUEST time (SSR is the
// paradigm's real shape, ADR-0002 §7), force-dynamic guarantees this route
// is never attempted at build time (no Cloudflare bindings exist then) and
// is re-rendered fresh on every request. NO loading.tsx and NO Suspense on
// this route, deliberately: streaming locks the HTTP status before
// `notFound()` can set it (Next's own docs, loading.md), and the slug
// contract below REQUIRES a real 404.
export const dynamic = "force-dynamic";

/**
 * The URL contract (pdp-build, settled): slug-keyed
 * /react-next/pdp/{id}-{artist}-{title}/. Parse the LEADING id, fetch the
 * tray, then verify the tray's slug equals the requested slug, any
 * mismatch is a 404, matching what static generation does by construction
 * (vanilla has no file at a non-canonical slug). A canonical 301 was
 * REJECTED: the build-time variants cannot serve one, so it would be an
 * observable behavioural divergence between paradigms on the very surface
 * that measures them.
 */
const loadPage = cache(async (slug: string): Promise<ReleaseDetail | null> => {
  const id = /^(\d{1,15})-/.exec(slug)?.[1];
  if (!id) return null;
  const detail = await loadDetail(Number(id));
  return detail && detail.slug === slug ? detail : null;
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const d = await loadPage(slug);
  // Never notFound() here: a notFound() thrown during METADATA resolution
  // bails to Next's own `__next_error__` document instead of the segment's
  // not-found boundary (measured on the composed plane, the 404 lost the
  // branded shell AND the chrome slot). The page component below owns the
  // throw; this only titles whichever page that produces.
  return {
    title: d
      ? `${d.title} · ${d.artist} · Long Decay Records`
      : "This record isn't in the crate · Long Decay Records",
  };
}

export default async function PdpPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const detail = await loadPage(slug);
  if (!detail) notFound();

  return (
    <Shell current="plp">
      <PdpArticle detail={detail} />
    </Shell>
  );
}

// variants/qwik/src/routes/pdp/[slug]/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import { PdpArticle } from "../../../components/PdpArticle";
import { Shell } from "../../../components/Shell";
import { type EdgeEnv, loadPdpDetail, projectPdpDetail } from "../../../lib/edge";

/**
 * /qwik/pdp/{slug}/ — resumability on the surface where interactivity is
 * genuine (pdp-variants slice 3).
 *
 * The URL contract (pdp-build, settled): parse the LEADING id, fetch the
 * tray through the variant's own EDGE binding at request time, verify the
 * tray's slug equals the requested slug — any mismatch is a 404 via
 * `fail()`, matching what static generation does by construction; a
 * canonical 301 was REJECTED (build-time variants cannot serve one).
 * `fail(404)` keeps the visitor inside Long Decay Records' own chrome —
 * this variant CAN brand its 404 server-side, where react-next's
 * multiple-root-layout structure defers its branded boundary to hydration;
 * the STATUS is the cross-paradigm contract, the body is each variant's own
 * (both recorded). The loader PROJECTS to the fields the page renders (the
 * editorial projectFeatured reasoning: the whole loader result rides this
 * route's q-data.json to client-nav visitors).
 */
export const usePdp = routeLoader$(async ({ params, platform, fail }) => {
  const id = /^(\d{1,15})-/.exec(params.slug)?.[1];
  if (!id) return fail(404, { notFound: true as const });
  try {
    const detail = await loadPdpDetail(platform.env as unknown as EdgeEnv, Number(id));
    if (!detail || detail.slug !== params.slug) {
      return fail(404, { notFound: true as const });
    }
    return { detail: projectPdpDetail(detail) };
  } catch {
    // A live data-plane failure is a real runtime state on a request-time
    // variant: branded 503 inside the store's own chrome (the editorial
    // route's shape), never qwik-city's unbranded error page.
    return fail(503, { unavailable: true as const });
  }
});

export default component$(() => {
  const pdp = usePdp();

  if (pdp.value.failed) {
    return pdp.value.notFound ? (
      <Shell>
        <div class="pm-pdp">
          <h1>{"This record isn't in the crate"}</h1>
          <p>
            {"No release in the frozen snapshot matches this address. The catalogue is fixed at capture time — a link that changed is a link that broke, honestly."}
          </p>
          <p>
            <a href="/react-next/plp/plain/">Back to all records</a>
          </p>
        </div>
      </Shell>
    ) : (
      <Shell current="plp">
        <div class="pm-pdp">
          <h1>{"This page couldn't load"}</h1>
          <p>
            {"The store's data plane didn't answer. This is a simulated demo storefront — nothing was ordered, nothing was lost."}
          </p>
        </div>
      </Shell>
    );
  }

  return (
    <Shell current="plp">
      <PdpArticle detail={pdp.value.detail} />
    </Shell>
  );
});

export const head: DocumentHead = ({ resolveValue }) => {
  const pdp = resolveValue(usePdp);
  if (pdp.failed) {
    return {
      title: pdp.notFound
        ? "This record isn't in the crate — Long Decay Records"
        : "This page couldn't load — Long Decay Records",
    };
  }
  return { title: `${pdp.detail.title} — ${pdp.detail.artist} — Long Decay Records` };
};
