// variants/react-next/src/components/CartStatus.tsx
"use client";

import { useEffect, useState } from "react";
import { CART_ANNOUNCE_EVENT } from "../lib/cart";

interface AnnounceDetail {
  message: string;
}

/** The shell's live region (WCAG 4.1.3), a sibling of `<main>`, not inside
 *  it, so it is reached by event rather than prop. Starts empty (the
 *  canonical served state); a successful add anywhere on the page sets its
 *  text via the shared cart-announce event. */
export function CartStatus() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    const onAnnounce = (event: Event) => {
      const detail = (event as CustomEvent<AnnounceDetail>).detail;
      setMessage(detail.message);
    };
    window.addEventListener(CART_ANNOUNCE_EVENT, onAnnounce);
    return () => window.removeEventListener(CART_ANNOUNCE_EVENT, onAnnounce);
  }, []);

  return (
    <p className="pm-status" role="status" data-pm-status="">
      {message}
    </p>
  );
}

// variants/qwik/src/components/CartStatus.tsx
import { component$, useContext } from "@builder.io/qwik";
import { CartContext } from "../lib/cart";

/**
 * The shell's live region (WCAG 4.1.3), a sibling of `<main>`, not inside it.
 * Starts empty (the canonical served state); a successful add sets
 * `cart.message`, and because this is the only component that reads that
 * property, Qwik re-renders this element and nothing else.
 *
 * The announcement reaches the DOM as a JSX text child, never as HTML, the
 * contract requires `textContent` semantics, and the release title is tray
 * data (ADR-0002: frozen data is still external data).
 */
export const CartStatus = component$(() => {
  const cart = useContext(CartContext);
  return (
    <p class="pm-status" role="status" data-pm-status>
      {cart.message}
    </p>
  );
});
